// <auto-generated />
using System;
using ClientNotification.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ClientNotification.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ClientNotification.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("CreditNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreditNumber")
                        .IsUnique();

                    b.HasIndex("EMail")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500.0,
                            CreditNumber = "AA12345",
                            DueDate = new DateTime(2023, 2, 13, 13, 29, 16, 366, DateTimeKind.Local).AddTicks(6775),
                            EMail = "Random@example.com",
                            Name = "Jone Dou"
                        });
                });

            modelBuilder.Entity("ClientNotification.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MessageTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "{Creditnumber}\r\n\r\n \r\n\r\nDear {Name}\r\n\r\nPlease pay by {dueDate}\r\n\r\nThe amount {amount}\r\n\r\n \r\n\r\nGreetings Vexcash",
                            Name = "Reminder"
                        },
                        new
                        {
                            Id = 2,
                            Message = "Dear {Name}\r\n\r\nThank you for your recent application for a VEXCASH credit. Unfortunately, you do not meet our current criteria for credit approval. \r\n\r\nYour request for {Amount} euro credit was declined\r\n\r\nIf you feel that you have information that will make a difference in these two considerations, please write to us.\r\n",
                            Name = "Cancellation"
                        });
                });

            modelBuilder.Entity("ClientNotification.Domain.Entities.SendGridResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("SendGridResponses");
                });

            modelBuilder.Entity("ClientNotification.Domain.Entities.SendGridResponse", b =>
                {
                    b.HasOne("ClientNotification.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNotification.Domain.Entities.MessageTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Template");
                });
#pragma warning restore 612, 618
        }
    }
}
